services:
  nginx:
    image: nginx
    container_name: unravel_nginx
    volumes:
      - ./nginx/unravel.sublimeful.org.conf:/etc/nginx/conf.d/unravel.sublimeful.org.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - unravel
  unravel:
    image: unravel
    container_name: unravel
    build: .
    restart: unless-stopped
